edition = "2018"
version = "Two"
unstable_features = true

indent_style = "Block"
reorder_imports = true
combine_control_expr = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
use_field_init_shorthand = true
use_try_shorthand = true
merge_derives = true
struct_lit_single_line = false
wrap_comments = false
match_block_trailing_comma = false
condense_wildcard_suffixes = true

max_width = 95
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
